<?php
return array(
  'article/([0-9]+)/add_comment$' => 'comment/create/$1',
  'article/([0-9]+)/delete_comment/([0-9]+)$' => 'comment/delete/$1/$2',
  'article/([0-9]+)$' => 'article/view/$1',
  'category/([0-9]+)/page-([0-9]+)$' => 'category/view/$1/$2',
  'category/([0-9]+)$' => 'category/view/$1',
  'category$' => 'category/index',
  'user/register$' => 'user/register',
  'user/login$' => 'user/login',
  'user/logout$' => 'user/logout',
  'cabinet/edit$' => 'cabinet/edit',
  'cabinet$' => 'cabinet/index',
  'admin/article/delete/([0-9]+)$' => 'admin/articleDelete/$1',
  'admin/article/update/([0-9]+)$' => 'admin/articleUpdate/$1',
  'admin/article/create$' => 'admin/articleCreate',
  'admin/articles/page-([0-9]+)$' => 'admin/adminArticleIndex/$1',
  'admin/articles$' => 'admin/adminArticleIndex',
  'admin$' => 'admin/index',
  '404' => 'site/404',
  '' => 'site/index',
);